# SpringBoot 唯一的配置文件， YML 文件
server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_test?useSSL=false
    username: root
    password: Davy2018
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: userserver #user 服务的服务名称，注册到eureka使用
#  cloud:
#    nacos:
#      server-addr: localhost:8848 # nacos服务地址

eureka:
  client:
    service-url: # eureka Server的地址信息 ，服务注册使用
      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  type-aliases-package: com.example.user.model
  configuration:
    map-underscore-to-camel-case: true


