server:
  port: 10010

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka


#    register-with-eureka=false
#    eureka.client.fetch-registry=false

spring:
  application:
    name: gateway  # 服务名称，注册到eureka
  cloud:
    gateway:
      routes:
        - id: user-server # 路由标识，唯一
          uri: lb://userserver # 路由的目标地址，与eureka 注册的保持一致
          predicates: # Spring 提供11种route predicates factory
            - Path=/user/**  # 路径断言, 判断是否符合规则

        - id: order-server
          uri: lb://orderserver # 路由的目标地址，与eureka 注册的保持一致
          predicates:
            - Path=/order/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
      default-filters: # 对所有路由都生效
        - AddRequestHeader=Author, David. # key,value


